### ISSUE TITLE
Add Restana 

### ISSUE THREAD

**Issue by husayt** [fastify/benchmarks#100]
On https://github.com/the-benchmarker/web-frameworks benchmark there are nodejs frameworks which come faster than fastify (Restana, rayo, polka). Here Rayo and Polka come slower than Fastify. It will be great to add Restana here as well, to see how well they do this benchmark.

Also, it will be interesting to find out why Rayo and Polka come faster on [web frameworks benchmark](https://github.com/the-benchmarker/web-frameworks) but are slower here. Maybe this benchmark is somehow biased towards fastify?

**Comment by Eomm** [comment]
I think that the difference is due to the payload.

That repo uses a simple string as a response, our bench instead return an `application/json` response following how those frameworks suggest managing this kind of data-type.

**Comment by husayt** [comment]
Yes, most probably is. Having  Restana on this benchmark will clarify that
too.

Thanks for an amazing library.

**Comment by aichholzer** [comment]
@husayt -I am the author of `Rayo` and @Eomm answer is valid. There are, however, other factors that can influence the results. I'm also a contributor to this repository and after running the tests several times, I have seen the "winner" be different quite a few times. 
Entropy on the server running the tests can have great influence on the numbers as well.

If you browse the commit history you will see that `Rayo` and `Polka` held the crown a few times.

**Comment by jsumners** [comment]
Which highlights that benchmarks are just a measure of potential latency for only *one* part of your application.

**Comment by aichholzer** [comment]
Well said @jsumners

**Comment by husayt** [comment]
@aichholzer @jsumners absolutely agree. This is not about establishing if a framework x better than y. It is actually about bringing them together, so we can all learn from each other and improve node ecosystem together. 
Each framework has it's own flavor, making it suitable for particular tasks and thus together they are making Node Js ecosystem more complete.

Real competition is with other platforms/languages. We should aim to get node based web frameworks to be on the top of global benchmark table along with and above others written in c/cpp, rust, python, php. 

Thanks for all the effort and amazing work.

/cc @jkyberneees

**Comment by jkyberneees** [comment]
Hi @husayt , thanks for suggesting the addition of `restana` to this benchmarks list. 

I might also suggest to consider other alternatives to https://www.npmjs.com/package/autocannon as benchmark tool. 

I extend the greetings to the fastify team.
Best Regards

**Comment by aichholzer** [comment]
@jkyberneees -Feel free to open a PR to include Restana.
