### ISSUE TITLE
Replace autocannon

### ISSUE THREAD

**Issue by marcj** [fastify/benchmarks#122]
I was just trying various performance benchmarks comparing fastify etc and wanted to have a base-line first. So I picked a high-performance web server written in C++ with asio. I tried running the autocannon command in the README and was very surprised by the results. It showed 62k avg req/s. From my experience I know that that couldn't be true, so I picked a high-performance http benchmark tool for the job: [wrk](https://github.com/wg/wrk) and there we have it: numbers doubled to 147k req/s. Other high-performance http benchmark tools confirm this number.

Reason enough for me to benchmark fastify with wrk with 100 clients: ~`39177.6` req/s, [hey](https://github.com/rakyll/hey), [bombardier](https://github.com/codesenberg/bombardier) and [wrk2](https://github.com/giltene/wrk2) confirm that. It's slower than the results states in the README. How can that be that several well-known high-performance benchmark tools show drastically lower results? Well it's because autocanon cheats and obviously works incorrectly. It uses `pipelining` which basically writes 10 HTTP requests to the same socket buffer without waiting for previous requests. This allows several TCP improvements taking place which are unrealistic in real traffic. So let's disable that: Now autocanon shows as well something around `43439.28` req/s. What does autocanon show with pipelining `autocanon -p 10`? `74773.82` req/s. Remember the exact same command with `10` pipelining yields 62k req/s for my C++ server. That's ridiculous.

It's pretty clear that fastify is not faster than the high-performance c++ web server every well-known http benchmark tools clearly show that, yet autocanon suggests it is. This is mainly because of pipelining which other benchmarks tools didn't implement. This is highly misleading and should not be used, as seen by the numbers above.

So I wanted to suggest to replace autocanon with wrk since autocanon is obviously too slow and inaccurate to benchmark http servers.

A side note: Node's built-in http server is decent, however node's tcp client code is very slow. For example Node can only send up to 357k packets per seconds for a single client against a high-performance C++ tcp server. A C++ tcp client achieves here 15m packets per second. That's a hell of a lot difference. So that's just another indicator that benchmarks done via Node tcp client code are highly misleading and should be avoided, hence my suggestion to replace autocanon with wrk.

**Comment by mcollina** [comment]
The focus of this is to measure the overhead introduced by the framework on top of Node.js. There is no other goal and the results are not meant to be measured in absolute terms (never do that).

We use autocannon because it's way easier to manipulate in js. The result are not absolute, but totally relevant in respect to all the other frameworks. As you can see, we benchmarks only frameworks that do not have any C++ parts.

We do not aim to be techempower.
