### ISSUE TITLE
Move travis job to Github Actions

### ISSUE THREAD

**Issue by mcollina** [fastify/benchmarks#129]
as titled

**Comment by salesh** [comment]
Hello Matteo @mcollina. I see that current 

node_js:
  - "8"
  - "10"
  - "11"
And dist is  "dist": "xenial"

Should node versions be like this or add new ones? And regarding dist should only be ubuntu-latest?

**Comment by mcollina** [comment]
Use ubuntu latest and v12 and v14 onlh
