### ISSUE TITLE
Is node v6.11.3 supported?

### ISSUE THREAD

**Issue by jpwesselink** [fastify/benchmarks#16]
I tried to run benchmark on node-v6.11.3, and it seems that it needs `async` to work properly. 

```
$ node -v
v6.11.3
$ npm -v
3.10.10
$ benchmark 
/usr/local/lib/node_modules/fastify-benchmarks/lib/bench.js:7
const doBench = async (handler) => {
                      ^

SyntaxError: Unexpected token (

```

**Comment by cagataycali** [comment]
Ah, benchmarks depends async capability node 6.x isn't support for now

**Comment by cagataycali** [comment]
@delvedor, should we support node 6.x?

**Comment by delvedor** [comment]
Node v6 is the currently LTS and will also be used later when Node v8 will be the new LTS.
So in my opinion yes, we should support Node v6.
@mcollina?

**Comment by mcollina** [comment]
Node 8 will become active LTS by the end of October. Node 6 will remain active LTS until April 2018, and then go into maintenance.

I do not have a problem in using Node 8 for the time being for these benchmarks, as I just need to run them on Node 8. However, others might want to run this harness on Node 6 as well. I'm ok with that, if someone wants to do the job.
