### ISSUE TITLE
Print out a summary of the run

### ISSUE THREAD

**Issue by mcollina** [fastify/benchmarks#17]
Ideally it should emit a textual format, plus something that can be copy-pasted to https://github.com/fastify/fastify#benchmarks.

**Comment by cagataycali** [comment]
<img width="399" alt="screen shot 2017-09-12 at 17 42 21" src="https://user-images.githubusercontent.com/9213230/30331939-c3409928-97e1-11e7-8411-d547828f9b08.png">

Is that what you want?

**Comment by mcollina** [comment]
I would prefer to have something like:

```
$ node benchmark.js stats
fastify XXX req/s YYY stdev
express XXX req/s YYY stdev
hapi XXX req/s YYY stdev
..
```

You can also format them using https://www.npmjs.com/package/table. See autocannon code for an example: https://github.com/mcollina/autocannon/blob/master/lib/progressTracker.js#L77-L89

**Comment by cagataycali** [comment]
Is that enough for `compare` command?
I will do it as a new command as you say. `stats`

**Comment by aichholzer** [comment]
This is now available using the `compare -t` commnad. See [Readme.md](https://github.com/fastify/benchmarks/blob/master/README.md) for details.

**Comment by aichholzer** [comment]
@mcollina -Closing this one as it's already available. Please feel free to ping me in case I am missing something.
