### ISSUE TITLE
Add support to ESM

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/benchmarks#220]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Frequently modules are dropping support to CommonJS and in order to keep it up to date, we should support the ESM as soon as possible

### Motivation

https://github.com/fastify/benchmarks/pull/216

**Comment by jsumners** [comment]
I rather just remove the offending modules.

**Comment by ikmrgrv** [comment]
> I rather just remove the offending modules.

What's wrong with keeping things up-to-date and dropping legacy supports ??
Just curious to know what's the pain point in adding support to ESM. If possible, what could be the strategy and how can I help to bring this upgrade ??

**Comment by jsumners** [comment]
1. CJS isn't "legacy"
2. ESM does not work the same way
3. ESM is not instrumentable
