### ISSUE TITLE
Reported throughput very low

### ISSUE THREAD

**Issue by love-lena** [fastify/benchmarks#233]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

-

### Node.js version

-

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

-

### Description

The reported req/sec is less than 100 for all services.
Fastify is reporting 59 req/sec, as opposed to the normal ~58000 req/sec

## Currently:
https://www.fastify.io/benchmarks/
<img width="903" alt="image" src="https://user-images.githubusercontent.com/79774482/157338128-640bd828-69dc-426d-9920-4bb270a3059a.png">

## From wayback machine
https://web.archive.org/web/20220214222812/https://www.fastify.io/benchmarks/
<img width="898" alt="image" src="https://user-images.githubusercontent.com/79774482/157338158-9641182a-fa5d-4972-b8e7-dbc39d2f4014.png">

### Steps to Reproduce

Visit https://www.fastify.io/benchmarks/

### Expected Behavior

~10,000s of req/sec

**Comment by love-lena** [comment]
If this is a "good first issue" I could have a crack at it. I've just picked up fastify recently so no promises. Anything I need to know about this package?

**Comment by Eomm** [comment]
The pipeline shows a lot of errors: https://github.com/fastify/benchmarks/runs/5476672680?check_suite_focus=true

We should understand what has changed in the GH pipelines that have triggered this error. Maybe the default node.js version has been updated?

**Comment by love-lena** [comment]
It actually looks like there were huge amounts of errors even before the numbers tanked.
Like 160,000 lines of
```
(node:2441) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:2441) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
```

**Comment by Eomm** [comment]
> Are these known/okay?

I don't think so 😞 

cc @fastify/benchmarks

**Comment by RafaelGSS** [comment]
@love-lena I would run each of those benchmarks individually until finding the one who's showing those warnings

**Comment by love-lena** [comment]
Well we can see from the logs that it is `express-route-prefix`. But even when running just one test by itself, I get numbers in the 10s. I think there are two different errors going on, but I am continuing to investigate.

**Comment by RafaelGSS** [comment]
I think so

**Comment by luisorbaiceta** [comment]
Don't have permissions to re-trigger builds in CircleCI @mcollina

**Comment by RafaelGSS** [comment]
It's fixed. Thank you!
