### ISSUE TITLE
Add support to hyper-express

### ISSUE THREAD

**Issue by dougg0k** [fastify/benchmarks#289]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

https://github.com/kartikk221/hyper-express

### Motivation

Fast option!

### Example

```
const HyperExpress = require("hyper-express");
const app = new HyperExpress.Server();

app.get("/", (_, response) => {
  response.json({ hello: 'world' });
});

app.listen(3000);
```

**Comment by RafaelGSS** [comment]
Would you want to submit a PR?

**Comment by dougg0k** [comment]
Done https://github.com/fastify/benchmarks/pull/290

**Comment by Eomm** [comment]
I would suggest to add it here: https://www.techempower.com/benchmarks/#section=data-r21&l=zik0sf-6bj&p=zik0zj-zijocf-zik0zj-zik0zj-4fti4f

It compares all the frameworks across languages
