### ISSUE TITLE
Update external Fastify benchmarks

### ISSUE THREAD

**Issue by Eomm** [fastify/benchmarks#291]
This famous first google result about frameworks show data about fastify v3:

https://www.techempower.com/benchmarks/#section=data-r21&l=zik0sf-6bj&p=zik0zj-zijocf-zik0zj-zik0zj-4fti4f

We should update the code to fastify v4:

https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/JavaScript/fastify

**Comment by dancastillo** [comment]
hey @Eomm id like to take this one here is [PR](https://github.com/TechEmpower/FrameworkBenchmarks/pull/7965)

**Comment by Eomm** [comment]
Great, thks!

Let's monitor the PR before closing!

- https://github.com/TechEmpower/FrameworkBenchmarks/pull/7965

**Comment by dancastillo** [comment]
@Eomm looks like it was merged in

**Comment by Eomm** [comment]
the result will be available in 117 hours 😱 

<img width="273" alt="image" src="https://user-images.githubusercontent.com/11404065/222359875-55b3521f-9c2f-4074-9b75-947b4367c18b.png">

https://tfb-status.techempower.com/results/5d76ba12-fb30-4f3f-9d44-1ffcdfa142b7

See you next week 😄
