### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by melroy89** [fastify/benchmarks#332]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I notice you tagged a release for benchmarks. The latest release however is from 2019.

**Comment by mcollina** [comment]
That was a mistake and it should not have been released. What would you expect in a release?

**Comment by melroy89** [comment]
Ow then maybe remove that release.

I expect a stable test framework I think. With the latest results that are validated.
