### ISSUE TITLE
False benchmarks

### ISSUE THREAD

**Issue by orubel** [fastify/benchmarks#369]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x.x

### Plugin version

1.x.x

### Node.js version

18.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

21

### Description

Fastifys benchmarks use a HIGH-END machine (show the number cores, GHZ, and memory being used) and send back a STATIC HARDCODED  response. This is NOT how you run your api backend because it will be hooked up DB, have security (gateway).
When it was run with a DB connection, it HALVED the numbers.

### Link to code that reproduces the bug

fastify/fastify#3617

### Expected Behavior

bench needs to be run with DB backend (non static hardcoded values) and environment needs to be shown so people can duplicate on similar hardware https://www.linkedin.com/feed/update/urn:li:activity:7272019383311302656/

**Comment by orubel** [comment]
This actually effects every benchmark... I just couldn't put that in there

Try benchmarkinbg with something decent like beapi_bench

**Comment by jsumners** [comment]
The test system is clearly documented and the source code readily available. This should be enough to draw your own conclusions.

**Comment by orubel** [comment]
Yeah I know. I used your benchmarks in my book to show how NOT to do benchmarks. You didn'y state what machine you were on, the GHZ, the number of cores or that your 'benchmark' uses hardcoded static return data (no DB connection)

**Comment by orubel** [comment]
I understand but when you brag about 47000/rps but no one can duplicate because they don't knoiw what machine you tested on it's a bad bench.

Plus hardcoding return dataset rather than using a DB is NOT a production environment so again, bad benchmark.

I tested Fastify (for my book) and didn't even come close to those numbers... and using a DB cuts the numbers in HALF
![Screenshot from 2024-12-09 09-58-05](https://github.com/user-attachments/assets/9f8bc39e-3117-4b8f-ac4a-67ed5b67d211)

**Comment by mcollina** [comment]
This repository and all others from Fastify are maintained by a group of volunteers. If you want to contribute _better benchmarks_, those would be welcomed as well.

I would recommend you to:

1. apologize and delete these issue, which are borderline on what is acceptable under our [CoC](https://github.com/fastify/.github/blob/main/CODE_OF_CONDUCT.md). 
2. you ask (politely!) the questions on _why_ certain things are set up in a given way, maybe there is a reason.

You seem to be trying to attack others to promote your book and are not here for a productive conversation.

**Comment by orubel** [comment]
Why would I delete? I am asking for 'accuracy'. These are made politely and there is no harassment (until you demanded I delete)

**Comment by jsumners** [comment]
You seem to be missing the point of these benchmarks. They show the performance difference in various _HTTP_ frameworks. They are _not_ designed to replicate some hypothetical "production" case. Including calls to external systems (even if they are a process on the same computer) would introduce variability that could not be accounted for and would obscure the purpose of these benchmarks. 

If you think you can devise a more appropriate benchmark that satisfies the stated purpose, you're welcome to propose such changes. As it stands, any further antagonistic behavior will result in a ban from the org.

**Comment by orubel** [comment]
> You seem to be missing the point of these benchmarks. They show the performance difference in various _HTTP_ frameworks. 

Against a tool that is hardcoding its return set to artificially increase its speed.

I would be more than happy to do a comparison benchmark if you used a DB and proper security. 

Just using a DB drops your stats by HALF. I suspect security would drop it by another half

**Comment by mcollina** [comment]
Those benchmarks are built to be a comparison against all the listed frameworks, to measure the overhead of each one. They are not claiming anything but the relative gap between the various listed JS frameworks.

As said, adding a DB or security or any other matter to _all_ frameworks would create more variability and make that comparison even harder.

—-

If you don’t recognize how your behavior is against our CoC and _definitely_ does not promote an healthy collaboration environment, then I would recommend some self-introspection. Everyone here is a volunteer: if you want to contribute, everyone is welcomed. If you want to disparage the work of volunteers, then you are definitely not welcome.

**Comment by orubel** [comment]
> As said, adding a DB or security or any other matter to _all_ frameworks would create more variability and make that comparison even harder.

Exactly. Benchmarking is not easy. But we do it to get a REALISTIC COMPARISON of a 'deployable' tool. 

What you created is not deployable by any sense of the word.
