### ISSUE TITLE
micro benchmark

### ISSUE THREAD

**Issue by dotcypress** [fastify/benchmarks#41]
I start playing with project and create new `micro` benchmark with another router, and on my machine it was a little bit faster than original one.

```js
'use strict'

const micro = require('micro')
const dispatch = require('micro-route/dispatch')

const server = micro(
  dispatch('/', 'GET', (req, res) => {
    return micro.send(res, 200, { hello: 'world' })
  })
)

server.listen(3000)
```

Does it make any sense to send PR with new benchmark?

**Comment by mcollina** [comment]
Sure, go ahead!

**Comment by dotcypress** [comment]
[Done](https://github.com/fastify/benchmarks/pull/42)!
