### ISSUE TITLE
Consider adding a benchmark to techempower.com

### ISSUE THREAD

**Issue by styfle** [fastify/benchmarks#65]
This website compares [many web server frameworks](https://twitter.com/ben_a_adams/status/1016386841644331010) and it might be useful to add fastify to this benchmark if it performs better than the node.js core http module.

https://www.techempower.com/benchmarks

**Comment by aichholzer** [comment]
Those benchmarks are anything but accurate. They compare apples to oranges and there is no point to get into those numbers/metrics.

**Comment by styfle** [comment]
Why do you say that? Can you elaborate?

**Comment by Nepoxx** [comment]
@aichholzer I wouldn't mind getting Fastify on there for you unless you have strong objections?

**Comment by aichholzer** [comment]
@Nepoxx -No objections at all, I maintain this repository, not my call to object or not. Speaking of which and to answer @styfle question; the techempower benchmarks are, IMO, nothing to go by as they do not compare things on a "fair" basis, meaning they do compare all sorts of frameworks for the sake of speed. Having that said, you cannot compare C++ to Nodejs or stuff that uses multi-core, by default, against stuff that does not.

Having that said, @Nepoxx feel free to PR Fastify into it (techempower).

**Comment by Nepoxx** [comment]
Alright I'll do that.

By the way, the techempower benchmarks, while not perfect, do account for multithreading as the node examples use the cluster module. Its really up to the people writing the benchmarks to account for it (and other things).

**Comment by aichholzer** [comment]
Alright, thank you.
I am aware of the `cluster`, nonetheless it is still does not seem like a fair/good comparison in my opinion.
