### ISSUE TITLE
Mention the impact of schema use on performance

### ISSUE THREAD

**Issue by abenhamdine** [fastify/benchmarks#7]
Newcomers to fastify are likely to be particularly interested in performance gain over other frameworks (and the [introducing article](https://thenewstack.io/introducing-fastify-speedy-node-js-web-framework/) emphasizes that).

So IMHO, it's better to be the more precise & transparent on how to achieve this performance level.

One main advantage of fastify seems to be its stringify module (https://github.com/fastify/fast-json-stringify), however currently this module will be only used if a schema is provided.

In my tests, I noticed a 25% perf gain by specifying a schema.

So I think it would be mentioned somewhere.

**Comment by abenhamdine** [comment]
Perhaps it would be preferable to see if there's still a performance gap after https://github.com/fastify/fastify/pull/192 has been merged

**Comment by delvedor** [comment]
It is all written in the [docs](https://github.com/fastify/fastify/blob/master/docs/Validation-And-Serialize.md#serialize) :)

**Comment by abenhamdine** [comment]
> It is all written in the docs :)  

Yes you're right, but not so easy to find for a newcomer 😉 
People often only read tl;dr or article on Medium, and don't go further.

**Comment by cagataycali** [comment]
Is issue has any purpose or advice, how we can improve this situation?

**Comment by abenhamdine** [comment]
I just have run my simple benchmark with fastify last release 0.27 (https://github.com/abenhamdine/frameworks-benchmark) and there's still a significant performance difference (roughly 15%)  with or without schema validation : 

```
$ npm run test-perf-fastify

> frameworks-benchmark@0.0.0 test-perf-fastify C:\node-projects\frameworks-benchmark
> autocannon -c 100 -d 5 localhost:3000/big && autocannon -c 100 -d 5 localhost:3000/bigschema 

Running 5s test @ http://localhost:3000/big
100 connections

Stat         Avg    Stdev   Max
Latency (ms) 194.49 13.32   238
Req/Sec      507.8  26.2    533
Bytes/Sec    86 MB  4.59 MB 92.3 MB

3k requests in 5s, 434 MB read

Running 5s test @ http://localhost:3000/bigschema
100 connections

Stat         Avg     Stdev   Max
Latency (ms) 171.4   10.6    215
Req/Sec      580.21  39.6    600
Bytes/Sec    70.7 MB 5.45 MB 75.5 MB

3k requests in 5s, 345 MB read
`` 

So I still think it would be mentioned somewhere or someone could be disappointed with performance on big responses without enabling schema validation.
