### ISSUE TITLE
add nest.js framework

### ISSUE THREAD

**Issue by zuohuadong** [fastify/benchmarks#71]
add nest.js framework
https://github.com/nestjs/nest

**Comment by aichholzer** [comment]
Thank you @zuohuadong but I agree with @cemremengu
Closing this one.

**Comment by muuvmuuv** [comment]
For those who are curious how the benchmark would look like:

- How many connections do you need? 100
- How many pipelines do you need? 10
- How long should it take? 40

```
┌──────────────┬────────┬─────────────┬─────────────┬───────────────┐
│              │ Router │ Requests/s  │ Latency     │ Throughput/Mb │
│              │        │ (% of bare) │ (% of bare) │ (% of bare)   │
├──────────────┼────────┼─────────────┼─────────────┼───────────────┤
│ bare         │ ✗      │ 56439.2     │ 1.71        │ 8.83          │
│              │        │ (100.00)    │ (100.00)    │ (100.00)      │
├──────────────┼────────┼─────────────┼─────────────┼───────────────┤
│ fastify      │ ✓      │ 52571.2     │ 1.84        │ 8.22          │
│              │        │ (93.15)     │ (107.60)    │ (93.15)       │
├──────────────┼────────┼─────────────┼─────────────┼───────────────┤
│ nest-fastify │ ✓      │ 52370.4     │ 1.85        │ 7.64          │
│              │        │ (92.79)     │ (108.19)    │ (86.56)       │
├──────────────┼────────┼─────────────┼─────────────┼───────────────┤
│ express      │ ✓      │ 32822.81    │ 2.97        │ 5.13          │
│              │        │ (58.16)     │ (173.68)    │ (58.16)       │
├──────────────┼────────┼─────────────┼─────────────┼───────────────┤
│ nest-express │ ✓      │ 25530.5     │ 3.84        │ 5.26          │
│              │        │ (45.24)     │ (224.56)    │ (59.58)       │
└──────────────┴────────┴─────────────┴─────────────┴───────────────┘
```

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by muuvmuuv** [comment]
No, sorry. I wrote it in TypeScript, compiled it and made minor changes to the benchmark scripts to get it working and don't want to fine tune it actually. It was just to have a simple overview but I can zip and send the code if you want?

**Comment by mcollina** [comment]
no need :)

Il giorno mer 12 feb 2020 alle ore 13:30 Marvin Heilemann <
notifications@github.com> ha scritto:

**Comment by muuvmuuv** [comment]
Found those benchmarks here which are very detailed. Look how fastify is even faster than Python frameworks 😨 

https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=db&l=zijz7j-e&p=zik0zj-zik0zj-zijunz-4fti4f&c=5&d=9 (remove filter to see aaaaall frameworks)
