### ISSUE TITLE
Installation Error Node `v10.15.1`

### ISSUE THREAD

**Issue by IslamWahid** [fastify/benchmarks#83]
I am facing an error while installing it using `npm i -g fastify-benchmarks`

node version: `v10.15.1`
npm version: `6.4.1`
nvm version: `0.33.11`
OS: macOS High Sierra version `10.13.6`

complete npm log:
[2019-02-19T14_47_28_232Z-debug.log](https://github.com/fastify/benchmarks/files/2880499/2019-02-19T14_47_28_232Z-debug.log)

**Comment by aichholzer** [comment]
@IslamWahid -Thank you for that. I will have a look.

**Comment by mcollina** [comment]
I do not have publish right to update that package, I'll look into getting them from npm.

We do not support Node 6 here anyway.

**Comment by aichholzer** [comment]
@IslamWahid 
```
npm i -g fastify-benchmarks
```
https://www.npmjs.com/package/fastify-benchmarks
I just released `V1` which should fix this issue for both Node `V8` and `V10`.

Let me know how it goes.

**Comment by IslamWahid** [comment]
@aichholzer thank you for the fix, now it's successfully installed.
