### ISSUE TITLE
Maintainers to issue a release

### ISSUE THREAD

**Issue by mcollina** [fastify/benchmarks#84]
Hi Folks,

I got npm publish rights from @cagataycali! Thanks!

Is there a volunteer that would help in cutting releases of this module, so we can fix https://github.com/fastify/benchmarks/issues/83?

There is problem a bunch of changes to make in the README to make it easily installable.

Thanks

Matteo

**Comment by aichholzer** [comment]
@mcollina -Happy to help if needed.

**Comment by mcollina** [comment]
Is this you https://www.npmjs.com/~aichholzer?

**Comment by aichholzer** [comment]
@mcollina -Yep.

**Comment by mcollina** [comment]
Done! Can you enable NPM 2FA?
