### ISSUE TITLE
Split `fastify` into `fastify1` and `fastify2`

### ISSUE THREAD

**Issue by allevo** [fastify/benchmarks#94]
As titled.

We should compare the two versions too!

**Comment by kibertoad** [comment]
What about v3?

**Comment by jsumners** [comment]
Why? I could accept an argument for benchmarking our current LTS versions. At this time that would mean only v2. Once v3 is released it would be v2 and v3 for 6 months. But then we have to update the benchmarks to show only v3 after v2 is no longer supported.

I think it's simpler to just show a benchmark for the most current supported version of Fastify.
