### ISSUE TITLE
add go framework 

### ISSUE THREAD

**Issue by zuohuadong** [fastify/benchmarks#97]
![](https://github.com/kataras/iris/raw/master/_benchmarks/benchmarks_graph_22_october_2018_gray.png)

The node.js performance is not much worse than golang.
Nodejs 12 (v8 7.4 and llhttp) has a significant performance boost.

Add go framework to let more people know that fastify is fast enough.

add  iris(go)  bin(go)  beego(go)

**Comment by delvedor** [comment]
Hello!
The aim of this benchmarks is to compare Node.js frameworks only, if you want to see benchmarks comparison between frameworks from different languages, I suggest you take a look [here](https://www.techempower.com/benchmarks/).
