### ISSUE TITLE
response time

### ISSUE THREAD

**Issue by prashantbhat84** [fastify/benchmarks#99]
Hello Team,

Just wanted to know the response time of fastify in comparison to other node.js frameworks??

**Comment by Eomm** [comment]
The timings written in the readme of this repo are produced with a service that replies "hello world".

Is this the question?

**Comment by prashantbhat84** [comment]
> The timings written in the readme of this repo are produced with a service that replies "hello world".
> 
> Is this the question

**Comment by prashantbhat84** [comment]
Yes, Thanks
